// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJxVGUzFtsRHoVJtrT0BzRckRXA4f9d5A',
    appId: '1:1211820864:web:62c95a0b4e83625250e8a5',
    messagingSenderId: '1211820864',
    projectId: 'gallary-9ba01',
    authDomain: 'gallary-9ba01.firebaseapp.com',
    storageBucket: 'gallary-9ba01.appspot.com',
    measurementId: 'G-39CG5554GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbsbWpb-MUvDjavFjnKACMX67tNefRPE',
    appId: '1:1211820864:android:8b60290520c9b94250e8a5',
    messagingSenderId: '1211820864',
    projectId: 'gallary-9ba01',
    storageBucket: 'gallary-9ba01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpKlD7ifwKIIkE7W9UFRwuEDP5lC_V5CY',
    appId: '1:1211820864:ios:52e8c5a1c1c6675650e8a5',
    messagingSenderId: '1211820864',
    projectId: 'gallary-9ba01',
    storageBucket: 'gallary-9ba01.appspot.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpKlD7ifwKIIkE7W9UFRwuEDP5lC_V5CY',
    appId: '1:1211820864:ios:52e8c5a1c1c6675650e8a5',
    messagingSenderId: '1211820864',
    projectId: 'gallary-9ba01',
    storageBucket: 'gallary-9ba01.appspot.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJxVGUzFtsRHoVJtrT0BzRckRXA4f9d5A',
    appId: '1:1211820864:web:b5107393ab1c63f350e8a5',
    messagingSenderId: '1211820864',
    projectId: 'gallary-9ba01',
    authDomain: 'gallary-9ba01.firebaseapp.com',
    storageBucket: 'gallary-9ba01.appspot.com',
    measurementId: 'G-72SSX85SHB',
  );
}
